### PR TITLE
Making code more readable...

### PR DESCRIPTION
**Pull request by wilhelmeek**
Just making the code a little more readable @ramshaw888.

### CODE REVIEW

**Review by ramshaw888 — DISMISSED** [review]
please no

**Comment by tomatosource** [comment]
Would love this integrated, would take this repo to the next level

**Comment by martyla** [comment]
Great diff, lets get this live ASAP

**Comment by Press-Play** [comment]
Can we get this merged? Would be amazing!

**Review by ramshaw888 — CHANGES_REQUESTED** [review]
Merge conflicts, please rebase.

**Comment by wilhelmeek** [comment]
this community isn't as good as it used to be. it has become toxic so I am moving to another project 

I am sad because i still can't turn on my lights @bellol

**Comment by martyla** [comment]
@wilhelmeek offered a great solution.

Instead of merging, the lead developer decides to do a weekend rewrite and breaks the existing API

Will be forking soon as "hue clapper classic"

**Comment by bellol** [comment]
@martyla please keep me updated on the project. would love to help contribute to make hue clapper great again

**Comment by bellol** [comment]
@martyla any updates on hue clapper classic?

**Comment by tomatosource** [comment]
> this community isn't as good as it used to be.

@here doesn't anyone have any work to do?

**Comment by tomatosource** [comment]
sorry Mr. @here

**Comment by ramshaw888** [comment]
> Merge conflicts, please rebase.

**Comment by ramshaw888** [comment]
Also, no merge commits in this repo thanks.

**Review by tomatosource — CHANGES_REQUESTED** [review]
to get off my work queue

**Comment by bellol** [comment]
@martyla 	any update on hue clapper classic?

**Comment by martyla** [comment]
> @martyla any update on hue clapper classic?

Almost there @bellol -- the code needed a complete rewrite of the core so it will be a bit longer, hang tight

**Pull request closed without merging**
