### PR TITLE
Readme Update

### PR DESCRIPTION
**Pull request by wilhelmeek**

### CODE REVIEW

**Comment by wilhelmeek** [comment]
Hey @ramshaw888, can you please take a look at this.

**Comment by ramshaw888** [comment]
Merged. This was a solid 0.1x pr

**Comment by wilhelmeek** [comment]
Dear Mr @ramshaw888 

You closed this and did not merge.  Can you please update.

Thank you

**Comment by ramshaw888** [comment]
No, I have squashed and merged.

**Pull request closed without merging**
